### ISSUE TITLE
1.16 Support

### ISSUE THREAD

**Issue by jewome62** [NaruseII/DeACoudre#1]
Bonjour, je sais que le plugin n'est plus maintenu, mais je voulais savoir les alternatives qui s'offrent à nous : 
 - Existe-t-il un plugin équivalent maintenu ?
 - Existe t-il un support payant ?
 - Est-il possible de mise à jour vers 1.16 de ce plugin
Sachant qu'il y a une belle exception : 
```
[03:37:03 ERROR]: Could not pass event InventoryClickEvent to DeACoudre v1.6.2
java.lang.NoSuchMethodError: 'java.lang.String org.bukkit.inventory.Inventory.getName()'
```

**Comment by NaruseII** [comment]
Le plugin a été refait entièrement et fonctionne avec toutes les versions au dessus de la 1.12 comprise.
